events {}
http {
  client_max_body_size 10m;
  server {
    listen 8080;
    location /v2/ {
      proxy_set_header Host $http_host;
      proxy_pass http://registry:5000;
    }
    location / { proxy_pass http://promoter:8081; }
  }
}
