[global]
    workgroup = CHARLIE
    server string = FS-CHARLIE File Server
    security = user
    map to guest = Bad User
    log level = 1

[public]
    comment = Public File Share
    path = /srv/shares/public
    browseable = yes
    read only = yes
    guest ok = yes

[it-configs]
    comment = IT Configuration Files
    path = /srv/shares/it-configs
    browseable = yes
    read only = yes
    guest ok = yes

[backup]
    comment = Backup Archives
    path = /srv/shares/backup
    browseable = yes
    read only = yes
    guest ok = yes
